using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MovingPlatform : MonoBehaviour
{
    [SerializeField] Vector3 delta;

    [SerializeField] float amplitude; //륶븴
    [SerializeField] float speed; //뫊뱗
    [SerializeField] float offset; //긆긲긜긞긣

    private Vector3 targetPosition;

    private Vector3 defaultPos;

    void Start()
    {
        defaultPos = transform.position;
    }

    void Update()
    {
        // 뫉뤾귩댷벍궠궧귡
        transform.position = defaultPos + delta * Mathf.Sin(Time.time + offset) * amplitude;
    }

    private void OnCollisionEnter(Collision other)
    {
        if (other.gameObject.CompareTag("Player"))
        {
            // 륢귢궫obj궻릂귩댷벍룿궸궥귡
            other.transform.SetParent(transform);
        }
    }
    private void OnCollisionExit(Collision other)
    {
        if (other.gameObject.CompareTag("Player"))
        {
            // 륢귢궫obj궻릂귩궶궘궥
            other.transform.SetParent(null);
        }
    }
}
