using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerTransparency : MonoBehaviour
{
    public Transform cameraTransform; // ƒJƒپƒ‰‚جTransform
    public Renderer playerRenderer;   // ƒvƒŒƒCƒ„پ[‚جRenderer
    public float distanceThreshold = 2.0f; // ”¼“§–¾‚ة‚·‚é‹——£‚ج‚µ‚«‚¢’l
    public float transparency = 0.5f; // ”¼“§–¾‚جƒAƒ‹ƒtƒ@’l

    [SerializeField] Material normalMaterial; // Œ³‚جƒ}ƒeƒٹƒAƒ‹
    [SerializeField] Material hantoumeiMaterial;

    void Start()
    {
        hantoumeiMaterial.color = new Color(1.0f, 1.0f, 1.0f, transparency);
    }

    void Update()
    {
        // ƒJƒپƒ‰‚ئƒvƒŒƒCƒ„پ[‚ج‹——£‚ًŒvژZ
        float distance = Vector3.Distance(cameraTransform.position, transform.position);

        if (distance < distanceThreshold)
        {
            if (playerRenderer.material != hantoumeiMaterial)
            {
                playerRenderer.material = hantoumeiMaterial;
            }

            playerRenderer.material.color = new Color(1.0f, 1.0f, 1.0f, distance / distanceThreshold * 0.5f);
        }
        else
        {
            if (playerRenderer.material != normalMaterial)
            {
                playerRenderer.material = normalMaterial;
            }
        }

    }
}
